apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "tailscale.fullname" . }}
subjects:
- kind: ServiceAccount
  name: "{{ include "tailscale.serviceAccountName" . }}"
roleRef:
  kind: Role
  name: {{ template "tailscale.fullname" . }}
  apiGroup: rbac.authorization.k8s.io